#!/bin/bash

# stripe trigger account.updated
# stripe trigger   balance.available
# stripe trigger   charge.captured
# stripe trigger   charge.dispute.created
# stripe trigger   charge.failed
# stripe trigger   charge.refunded
# stripe trigger   charge.succeeded
# stripe trigger   checkout.session.async_payment_failed
# stripe trigger   checkout.session.async_payment_succeeded
# stripe trigger   checkout.session.completed
# stripe trigger   customer.created
# stripe trigger   customer.deleted
# stripe trigger   customer.source.created
# stripe trigger   customer.source.updated
# stripe trigger   customer.subscription.created
# stripe trigger   customer.subscription.deleted
# stripe trigger   customer.subscription.updated
# stripe trigger   customer.updated
# stripe trigger   invoice.created
# stripe trigger   invoice.finalized
# stripe trigger   invoice.paid
# stripe trigger   invoice.payment_action_required
# stripe trigger   invoice.payment_failed
# stripe trigger   invoice.payment_succeeded
# stripe trigger   invoice.updated
# stripe trigger   issuing_authorization.request
# stripe trigger   issuing_card.created
# stripe trigger   issuing_cardholder.created
# stripe trigger   payment_intent.amount_capturable_updated
# stripe trigger   payment_intent.canceled
# stripe trigger   payment_intent.created
# stripe trigger   payment_intent.partially_funded
# stripe trigger   payment_intent.payment_failed
# stripe trigger   payment_intent.requires_action
# stripe trigger   payment_intent.succeeded
# stripe trigger   payment_link.created
# stripe trigger   payment_link.updated
# stripe trigger   payment_method.attached
# stripe trigger   payout.created
# stripe trigger   payout.updated
stripe trigger   plan.created
stripe trigger   plan.deleted
stripe trigger   plan.updated
# stripe trigger   price.created
# stripe trigger   price.updated
# stripe trigger   product.created
# stripe trigger   product.deleted
# stripe trigger   product.updated
# stripe trigger   quote.accepted
# stripe trigger   quote.canceled
# stripe trigger   quote.created
# stripe trigger   quote.finalized
# stripe trigger   setup_intent.canceled
# stripe trigger   setup_intent.created
# stripe trigger   setup_intent.setup_failed
# stripe trigger   setup_intent.succeeded
# stripe trigger   subscription_schedule.canceled
# stripe trigger   subscription_schedule.created
# stripe trigger   subscription_schedule.released
# stripe trigger   subscription_schedule.updated